### ISSUE TITLE
Consider dropping CR spec requirements 

### ISSUE THREAD

**Issue by jetvillegas** [browserext/browserext.github.io#1]
"As the specifications developed in the Community Group mature and as Browser Vendors confirm intent to implement them, it is expected that these specifications will be migrated to the appropirate W3C Working Group where they can be put on the Recommendation track with appropriate status and Intellectual Property (IP) considerations."

Consider dropping the expectation that browser extension specs follow the same Recommendation track that web content specifications do. The overhead of that process seems too heavy when a normative reference implementation and documentation would suffice, and likely be more useful to extension authors.

**Comment by frivoal** [comment]
I am not 100% sure we will go down that path, but I'd like to keep it open, as despite the overhead, the REC track does have benefits.

How about tweaking the wording to indicate that this is something we may to, rather than something we must do?
For example, 
```diff
- it is expected that these specifications will be migrated [...]
+ this community group may consider migrating them [...]
```

**Comment by frivoal** [comment]
Solved by https://github.com/browserext/browserext.github.io/commit/678c27e62d7c0ece357919ffd4f6934a6c03b9a9
