### ISSUE TITLE
Get feedback from browserext CG and WebDriver folks on proposed extensions

### ISSUE THREAD

**Issue by frivoal** [browserext/browserext.github.io#10]
Get feedback from the [browserext CG](mailto:public-browserext@w3.org) and [WebDriver folks](mailto:public-browser-tools-testing@w3.org) on proposed extensions to webdriver:

http://rawgit.com/dhbrett/webdriver/extensions_reduced/webdriver-spec.html

**Comment by frivoal** [comment]
The conclusion is that our approach is considered sound by the WebDriver people, but as this is a (fairly) independent extension, we should host it in our spec rather than theirs.

@mikepie1 Please close this issue once you've added the section to https://github.com/browserext/browserext/

**Comment by mikepie1** [comment]
Merged/added the WebDriver section in this commit
https://github.com/browserext/browserext/commit/756366cfd1a0f6ac5062c89e46f0c2cea1c81275
