### ISSUE TITLE
The BrowserExt CG could use a logo

### ISSUE THREAD

**Issue by frivoal** [browserext/browserext.github.io#12]
This CG doesn't have a logo. While this is not blocking discussions, having something would make us more easily identifiable, on the web and in social media.

Submissions from people who have more artistic sense than me (not hard) are much welcome.

**Comment by frivoal** [comment]
https://mikepie1.github.io/browserext-1/LogoIdeas.png

**Comment by frivoal** [comment]
Participants in the CG so far has expressed a preference for design 9 or 10 of the link above.

Mike is expected to do a new iteration based on them, including "X" or "Ext" in there somehow.

**Comment by frivoal** [comment]
Meeting minutes: http://browserext.github.io/minutes/2016-09-22.html

**Comment by frivoal** [comment]
https://mikepie1.github.io/browserext-1/LogoIdeas.png

**Comment by snoack** [comment]
Note that there is also a JavaScript UI framework, called [Ext](https://www.sencha.com/products/extjs). So I fear that if our logo shows the three letters "ext" (without the addition of "browser") this might cause confusion, or even trademark issues.

**Comment by frivoal** [comment]
I wasn't aware of that project, thanks. Their name is Ext JS, not just Ext, and "ext" alone is already a widely used set of three letters (even if we just stick to software projects), so it doesn't seem to me that anyone could lay a trademark claim and we should be good, but IANAL.

**Comment by frivoal** [comment]
As per our last meeting, @kmaglione should check with [the mozzila community design portal](https://github.com/mozilla/OpenDesign) to get feedback.

**Comment by frivoal** [comment]
Temporary styling uploaded. https://twitter.com/browserext

**Comment by frivoal** [comment]
We've had a logo for a while now, and nobody seems to be in a rush to improve upon it. Suggestions are still welcome, but this bug has outlived its usefulness. Closing.
