### ISSUE TITLE
Scope change - Desktop browser extensions

### ISSUE THREAD

**Issue by cyberphone** [browserext/browserext.github.io#13]
This suggestion is related to the discussions on native messaging but also on how Android applications are distributed.  There's little evidence that Chrome on Android ever will support the extension scheme of the desktop version since the latter is incompatible with both the OS and its security model.  Although my knowledge of iOS is rather limited, I believe the same would apply to iOS which effectively leaves us with Windows.

**Comment by frivoal** [comment]
If you are suggesting that we change the scope to include desktop browser extensions, this is not necessary, as they are already included.
If you are suggesting that we should exclude mobile browsers and only deal with extensions, I disagree. Although it is possible that the APIs or packaging format we specify end up being more practical on some platforms than on some others, I would strongly object to ruling out any platform or class of platform ahead of time.

**Comment by cyberphone** [comment]
It seems to me that it wouldn't be entirely unreasonable asking for input from the platform owners.

This public answer doesn't look too promising:
https://www.reddit.com/r/Android/comments/35v8gi/we_are_the_chrome_for_android_team_ama/cr8alzk

**Comment by frivoal** [comment]
I believe my statement above does reflect the consensus of the browser vendors involved in this CG. @mikepie1 @aswan @kmaglione @shwetank, please comment if you disagree (explicitly agreeing is OK too).

**Comment by cyberphone** [comment]
> I believe my statement above does reflect the consensus of the browser vendors involved in this CG.

Yes, but the latter currently represent a rather small share of the mobile browser market.  Anyway, it is actually the _combination_ of in-browser extensions and native messaging that worries me because that part seems even more unlikely to materialize in the mobile browser world.

**Comment by frivoal** [comment]
It is difficult to take into account the opinions of those who have declined to participate. Feature requests for google should be addressed to google.

I would like one clarification from you: do you wish the scope was restricted to speak only of desktop extensions? I would object to that. Do you believe the scope is currently restricted to speaking only of desktop extensions, and wish to extend it to non desktop as well? The word "desktop" does not appears in [the charter](https://browserext.github.io/charter/), so the scope is already not limited.

**Comment by cyberphone** [comment]
@frivoal Let me put it like this: What's in the charter or not is not such a big deal for me but from a practical point of view it seems that the target will be desktop browsers.  You can close this issue now.
