### ISSUE TITLE
Specify W3C Software and Document license

### ISSUE THREAD

**Issue by jetvillegas** [browserext/browserext.github.io#2]
"This group will develop specifications, possibly supported by test suites, and may also write notes. The exact list of documents that need to be written to achieve the group's goals is not fully determined at the time of writing this charter, and will be one of the first work items of this Community group."

Can you specify that this group publishes under this license?
http://www.w3.org/Consortium/Legal/2015/copyright-software-and-document

**Comment by frivoal** [comment]
Thanks, that is a very good point, sorry I missed that. I'll fix this soon.

**Comment by frivoal** [comment]
Fixed by https://github.com/browserext/browserext.github.io/commit/56feb6ee5f80eb32512e4c2e14063c8b940817c0
