### ISSUE TITLE
Start a new spec for Native messaging

### ISSUE THREAD

**Issue by frivoal** [browserext/browserext.github.io#5]
Native messaging is an important feature for many extension developers. Even though it is somewhat premature to expect a specification for native messaging while we the main specification for extensions is not yet sorted out, based on user demand, Mozilla is planning on shipping such a mechanism.

If implementations are going forward, we should have a spec, both to document what is being implemented, and to provide a discussion space to argue about the pros and cons of the various possible approaches, and guide implementers toward a better solution.

We will start a new specification, separate from http://browserext.github.io/browserext/ but having it as a dependency. Mozilla is willing to maintain it.
Proposed URL: http://browserext.github.io/native-messaging/

**This is a tentative resolution of the CG. If no dissenting opinion is expressed here within 10 days, this will be considered the consensus of the CG. Work on this item may begin before the 10 days are elapsed, but any such work will be rescinded if the eventual consensus disagrees with this tentative resolution.**

**Comment by cyberphone** [comment]
There is an unsolved problem here: None of the two vendors who together control more than 90% of the mobile OS market have expressed any sentiment for this solution (or any other solution either).

IMHO, "in-browser" extensions and Native messaging have quite different use-cases and security models making this a bad "combo".  If I were Mozilla I would raise this issue in TAG or WebAppSec before taking a next step.

**Comment by frivoal** [comment]
@cyberphone This is early stages, so it is not surprising that not all browser vendors are on board yet. We do have 3 of them in the CG who are in favor of at least exploring this approach, so I think we should proceed. As long as browser vendors are working on something, we're better off having it fully documented. This does not necessarily mean that we will ultimately stick with this approach, but it should help looking into its pros **and cons** at a more fine grained level, and so that we can either fix the problems, or decide after careful consideration that the whole thing was misguided.

I think your suggestion to approach the TAG and WebAppSec on this specific topic is a good one, and we should absolutely do so as soon as the spec for Native messaging that we're discussing here has sufficiently well outlined what it is trying to accomplish and how it proposes to do so.

In the meanwhile, I understand you're still not in favor of this approach, and would prefer that some other alternative be explored, and that seems perfectly reasonable to me as well. If you think that native messaging is best solved independently from browser extensions, then this CG is probably the wrong host for that discussion, and the [WICG](https://wicg.github.io/wicg.io/) is probably a better fit. With that said, if you do want to explore this here and other members are interested as well, that is certainly fine as well.

To capture your concerns, what would you think of noting an issue in the specification, maybe right before or right after the introduction, noting something like:

> Some people have expressed concerned that coupling native messaging and browser extensions may be the wrong way to solve the problem. Details about these concerns may be found at (link), (link) or (link). Suggestions on how to address these concerns within this specification, or through alternative proposals, are welcome.

**Comment by cyberphone** [comment]
_Background_: I'm currently using the intent system in Android which actually enables activation of native apps from the Web.  IMO, this system is insufficient for payment applications which is my line of work.

**Comment by cyberphone** [comment]
@frivoal If you take a peek at 23:00 of this recent Google I/O clip you will find a very different approach to native messaging:
https://www.youtube.com/watch?v=yelPlCVZLEE&feature=youtu.be

**Comment by frivoal** [comment]
@cyberphone Sorry for the (terribly) slow answer. Too many irons in the fire.

I am not sure I understand the parallel here. If I understand your video correctly, this specialized API is offered by the browser, not a way for extensions or web pages to communicate with arbitrary native processes of their choosing.

Anyway, even if I am not sure about this one in particular, I am sure that there are many other possible approaches to Native Messaging. But one particular approach was taken in chrome, and other browsers vendors want to explore reusing / refining that approach, so it makes sense to start a draft and look into that.

Do you wish for your concerns to be capture in a note in or near the introduction of that draft?

**Comment by cyberphone** [comment]
@frivoal There are as you say many possible approaches, maybe not to native messaging but to access to native code.  I have tried to list these: 
https://bugs.chromium.org/p/chromium/issues/detail?id=614658

It is IMO somewhat disturbing that the W3C folks specializing in Web architcture appear to be _uninterested_ in this topic:
https://lists.w3.org/Archives/Public/www-tag/2016Jun/0005.html
The general off-list response is "extensions are not a part of the open Web" which doesn't bode well for any effort in this space, including "browserext".

**Comment by frivoal** [comment]
I am surprised that the TAG won't talk about this indeed. Extensions haven't been a part of the open web, but we are trying to change that. Flash and friends were not open, but they were part of the web, and things that are trying to replace part of what they did in an open way certainly have their place in W3C discussions.

As far as I know the TAG is generally a reasonable group, so I suspect a misunderstanding or missing context rather than actual well thought out disagreement, but without seeing the off-list messages you're referring to, it's hard to tell.

**Comment by cyberphone** [comment]
Since the "browserext" CG already have a couple of browser vendor representatives on board, it seems that it should be a reasonable task for them digging a little bit further into this so we don't end-up with something that immediately gets deprecated.

Although I have specific preferences (which I can motivate), the market in general doesn't care anything about which native code access solution that eventually "wins".  The "localhost" schemes is BTW probably way more popular than Chrome's fairly recent Native Messaging.

**Comment by cyberphone** [comment]
Apple was the first browser vendor who "got it":
https://developer.apple.com/reference/applepayjs/applepaysession
They did it through a proprietary version of Native Messaging since the W3C in their wisdom have decided that "app access is not the Web".

**Comment by cyberphone** [comment]
After the somewhat heated discussions on the mailing list regarding the security of the W2NB proposal, I have given this some further thoughts.

Claim: The W2NB proposal has essentially the same security characteristics as Android's custom protocol handler scheme since they do the same thing; Starting a specific native "App" from a standard Web page.

The only (but crucial) thing W2NB adds to the picture is the ability to "talking" to the invoking Web page which in my opinion is not half as dangerous as being able to HTTP POST to any server out there which is what Apps can do.

Using W2NB such Apps would preferably rather communicate indirectly via the calling Web page (presumable using "fetch") , subject to _browser_ rules, like respecting CORS etc.  My payment prototype does this so it is tested as well.

**Comment by frivoal** [comment]
A stub spec has been set up, to be filled as we go. For now it's empty, but that's obviously meant to change.

Public URL: https://browserext.github.io/native-messaging/
github: https://github.com/browserext/native-messaging/
Editor: @aswan

@cyberphone: I invite you to register your concerns as issues on that repository so that they can be discussed and addressed individually.

@aswan: Have a look at what @cyberphone wrote above, it is relevant feedback for this topic.
